server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/microservice
  username: postgres
  password: 123

eureka:
  client:
    register-with-eureka: true                    #registers the service with eureka server
    fetch-registry: true                           #fetches the registry from the eureka server
    service-url:                                   #eureka server url
        defaultZone: http://localhost:8761/eureka/ #default zone
  instance:                                        #instance configuration for the service
    hostname: localhost